apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cars-api-github-listener-interceptor
spec:
  serviceAccountName: pipeline-run-service-accnt
  triggers:
    - name: cars-api-github-listener
      interceptors:
        - ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-interceptor-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["pull_request"]
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: cars-api-github-trigger-binding
      template:
        ref: cars-api-github-trigger-template
