apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-run-service-accnt
secrets:
  - name: cars-api-cicd-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: pipeline-run-service-accnt-kube-api-secret
  annotations:
    kubernetes.io/service-account.name: pipeline-run-service-accnt
type: kubernetes.io/service-account-token
