apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: cars-api-github-trigger-binding
spec:
  params:
    - name: cars-api-git-repo-url
      value: $(body.repository.clone_url)
    - name: cars-api-git-commit-id
      value: $(body.pull_request.head.sha)
