apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-cars-api-image
spec:
  inputs:
    resources:
      - name: source
        type: git
  outputs:
    resources:
      - name: image
        type: image
  stepTemplate:
  steps:
    - name: create-image-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=./source/Dockerfile"
        - "--destination=$(outputs.resources.image.url)"
        - "--context=$(inputs.resources.source.path)/"
